language: r
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
sudo: false
env:
  global:
  - secure: vJpQ1EDBDzS3SeG+FldlELKn5imE7lD1gXfs+sIUcRfwlp60i+r5WZIw9bTtpOj7LslaNxpUaspTnaKXGZQhYzYkL3XdLD2j3mP01IZkvvkXDFSeFVtJoue//iT4fG7zxcQq4kXmW57baMbE1Vu2An2+O27UTht2OLtpG9kC8JejPZ69VYnol4Y3KAlDdOR/eOg35Rpgbqj1x+5F3zhGkkCKxP0j1ZvE2afwpVf2Nxk02TISAmhSTxWFuS4/s+SPPmpRh0KVaJ78mUXPfr7lOWsjNiMigtEqcdyx4Qz0mUtE+dV6IphNVVXytLFnJ9wu2itiw5fL47/djDaySC+RLMSfPNuXB6EEsIAp8ep3FtFugnDTsuGJUBV3yg0AUF0yK/vC0wD//FNB0X81DtB4fGXBycXhxL+6JsWF0lSzG0YtTa4d3dSTfssz3aZipU2oS/2US6wBv9kz5hIsw0iLju1HHF2azKxQmc8O72sCOEeahkr2iJlWikqTOfFZtnowAYgT2UILch6GSkp316hnyCxJjrqYKTZkM5EO4C442q3oVLdlVTguzlmB2WYkVL8Clo6TO8oUr7difUxY4KAgi/A9nPPDc/KWwlJmPQ7b9+3rFvYdDZrZ92JX1JYg0nWu5sswe2buyZUlS0Os0xnPvQhWry3/4nP24hDwMQJFDBc=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
  
