language: r
cache:
  packages: true
sudo: false
addons:
  apt:
    packages:
      - libmagick++-dev

before_script:
- chmod +x ./_texlive.sh
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_texlive.sh"
- "./_build.sh"
- "./_deploy.sh"
